/* Available Tesseract.js languages. Code -> label.
 * Languages are downloaded on demand by the Tesseract worker the first time
 * a given language is selected, then cached by the browser for subsequent use.
 */
const LANGUAGES = {
  afr: "Afrikaans",
  amh: "Amharic",
  ara: "Arabic",
  asm: "Assamese",
  aze: "Azerbaijani",
  aze_cyrl: "Azerbaijani (Cyrillic)",
  bel: "Belarusian",
  ben: "Bengali",
  bod: "Tibetan",
  bos: "Bosnian",
  bre: "Breton",
  bul: "Bulgarian",
  cat: "Catalan",
  ceb: "Cebuano",
  ces: "Czech",
  chi_sim: "Chinese (Simplified)",
  chi_tra: "Chinese (Traditional)",
  chr: "Cherokee",
  cym: "Welsh",
  dan: "Danish",
  deu: "German",
  dzo: "Dzongkha",
  ell: "Greek",
  eng: "English",
  epo: "Esperanto",
  est: "Estonian",
  eus: "Basque",
  fao: "Faroese",
  fas: "Persian",
  fil: "Filipino",
  fin: "Finnish",
  fra: "French",
  fry: "Western Frisian",
  gla: "Scottish Gaelic",
  gle: "Irish",
  glg: "Galician",
  grc: "Ancient Greek",
  guj: "Gujarati",
  hat: "Haitian",
  heb: "Hebrew",
  hin: "Hindi",
  hrv: "Croatian",
  hun: "Hungarian",
  hye: "Armenian",
  iku: "Inuktitut",
  ind: "Indonesian",
  isl: "Icelandic",
  ita: "Italian",
  ita_old: "Italian (Old)",
  jav: "Javanese",
  jpn: "Japanese",
  kan: "Kannada",
  kat: "Georgian",
  kat_old: "Georgian (Old)",
  kaz: "Kazakh",
  khm: "Central Khmer",
  kir: "Kirghiz",
  kor: "Korean",
  kor_vert: "Korean (Vertical)",
  kur: "Kurdish",
  lao: "Lao",
  lat: "Latin",
  lav: "Latvian",
  lit: "Lithuanian",
  ltz: "Luxembourgish",
  mal: "Malayalam",
  mar: "Marathi",
  mkd: "Macedonian",
  mlt: "Maltese",
  mon: "Mongolian",
  mri: "Maori",
  msa: "Malay",
  mya: "Burmese",
  nep: "Nepali",
  nld: "Dutch",
  nor: "Norwegian",
  oci: "Occitan",
  ori: "Oriya",
  pan: "Panjabi",
  pol: "Polish",
  por: "Portuguese",
  pus: "Pushto",
  ron: "Romanian",
  rus: "Russian",
  san: "Sanskrit",
  sin: "Sinhala",
  slk: "Slovak",
  slv: "Slovenian",
  snd: "Sindhi",
  spa: "Spanish",
  spa_old: "Spanish (Old)",
  sqi: "Albanian",
  srp: "Serbian",
  srp_latn: "Serbian (Latin)",
  sun: "Sundanese",
  swa: "Swahili",
  swe: "Swedish",
  syr: "Syriac",
  tam: "Tamil",
  tel: "Telugu",
  tgk: "Tajik",
  tgl: "Tagalog",
  tha: "Thai",
  tir: "Tigrinya",
  ton: "Tonga",
  tur: "Turkish",
  uig: "Uighur",
  ukr: "Ukrainian",
  urd: "Urdu",
  uzb: "Uzbek",
  uzb_cyrl: "Uzbek (Cyrillic)",
  vie: "Vietnamese",
  yid: "Yiddish",
};

if (typeof window !== "undefined") {
  window.LANGUAGES = LANGUAGES;
}